package edu.umich.andykong.ptmshepherd.glyco;

import java.util.HashMap;
import java.util.TreeMap;

public class GlycanMasses {

    // Building blocks for glycan compositions
    public static final float hexnacMass = (float) 203.079037;
    public static final float hexMass = (float) 162.05282;
    public static final float dhexMass = (float) 146.057909;
    public static final float neuacMass = (float) 291.095417;
    public static final float neugcMass = (float) 307.090334;
    public static final float phosphoMass = (float) 79.96633;
    public static final float sulfoMass = (float) 79.95682;

    // map of residue -> mass
    public static TreeMap<GlycanResidue, Float> glycoMasses;
    static
    {
        glycoMasses = new TreeMap<>();
        glycoMasses.put(GlycanResidue.Hex, hexMass);
        glycoMasses.put(GlycanResidue.HexNAc, hexnacMass);
        glycoMasses.put(GlycanResidue.dHex, dhexMass);
        glycoMasses.put(GlycanResidue.NeuAc, neuacMass);
        glycoMasses.put(GlycanResidue.NeuGc, neugcMass);
        glycoMasses.put(GlycanResidue.Phospho, phosphoMass);
        glycoMasses.put(GlycanResidue.Sulfo, sulfoMass);
    }

    // lists of expected oxonium ions generated by given residue types
    // todo: calculate exactly and add all NeuGc, other ions
    public static final Float[] NeuAcOxoniums = {274.0921325f, 292.1026925f, 657.2349f};    // NeuAc - H2O, NeuAc, NeuAc + HexNAcHex
    public static final Float[] NeuGcOxoniums = {290.087f, 308.09761f, 673.230f};   // NeuGc - H2O, NeuGc, NeuGc + HexNAcHex
    public static final Float[] PhosphoOxoniums = {243.026426f, 405.079246f, 485.045576f};
    public static final Float[] SulfoOxoniums = {284.044f, 446.098f, 811.212f};

    // Map of names to residues for parsing database files. NOTE: assumed all lower case
    public static TreeMap<String, GlycanResidue> glycoNames;
    static
    {
        glycoNames = new TreeMap<>();
        glycoNames.put("hex", GlycanResidue.Hex);
        glycoNames.put("glc", GlycanResidue.Hex);
        glycoNames.put("gal", GlycanResidue.Hex);
        glycoNames.put("glucose", GlycanResidue.Hex);
        glycoNames.put("galactose", GlycanResidue.Hex);
        glycoNames.put("hexnac", GlycanResidue.HexNAc);
        glycoNames.put("glcnac", GlycanResidue.HexNAc);
        glycoNames.put("galnac", GlycanResidue.HexNAc);
        glycoNames.put("fuc", GlycanResidue.dHex);
        glycoNames.put("dhex", GlycanResidue.dHex);
        glycoNames.put("neuac", GlycanResidue.NeuAc);
        glycoNames.put("neugc", GlycanResidue.NeuGc);
        glycoNames.put("phospho", GlycanResidue.Phospho);
        glycoNames.put("phosphorylation", GlycanResidue.Phospho);
        glycoNames.put("phosphate", GlycanResidue.Phospho);
        glycoNames.put("sulf", GlycanResidue.Sulfo);
        glycoNames.put("sulfo", GlycanResidue.Sulfo);
        glycoNames.put("sulfation", GlycanResidue.Sulfo);
        glycoNames.put("sulfate", GlycanResidue.Sulfo);
    }
    public static HashMap<GlycanResidue, String> outputGlycoNames;
    static
    {
        outputGlycoNames = new HashMap<>();
        outputGlycoNames.put(GlycanResidue.Hex, "Hex");
        outputGlycoNames.put(GlycanResidue.HexNAc, "HexNAc");
        outputGlycoNames.put(GlycanResidue.dHex, "Fuc");
        outputGlycoNames.put(GlycanResidue.NeuAc, "NeuAc");
        outputGlycoNames.put(GlycanResidue.NeuGc, "NeuGc");
        outputGlycoNames.put(GlycanResidue.Phospho, "Phospho");
        outputGlycoNames.put(GlycanResidue.Sulfo, "Sulfo");
    }

}

